lang:
  customdrops:
    zapnute: '§aPráve si si §a§lzapól§a custom drops!'
    vypnute: '§aPráve si si §c§lvypól§a custom drops!'
drops:
  block:
    COBBLESTONE:
    - STONE:10
    - OAK_LEAVES:5
  mob:
    ZOMBIE:
    - STONE:10
    - OAK_LEAVES:5